set number
filetype on
syntax on
set autoindent
set cindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set smarttab
set expandtab
set cursorline
set hlsearch
set completeopt=preview,menu
set tags=./tags,tags;$HOME
set autochdir
